"""add partner fields

Revision ID: a0c85846e5d3
Revises: 0e8aedb99139
Create Date: 2025-12-05 22:53:59.029858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c85846e5d3'
down_revision = '0e8aedb99139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('partner_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('partner_locations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fee_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fee_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fee_max')
        batch_op.drop_column('fee_min')
        batch_op.drop_column('partner_locations')
        batch_op.drop_column('partner_category')
        batch_op.drop_column('nid')

    # ### end Alembic commands ###
